name: emergingpoopie
favicon: null
layout_spectrum: 0.71175
typography_spectrum: 0.40351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#718490'
    - '#424d56'
    - '#dbe0e3'
    - '#bded56'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
